<?php

declare(strict_types=1);

namespace Homework\Tests;

use PHPUnit\Framework\TestCase;

/**
 * Class HomeworkTest
 * @package FizzBuzzTest\Tests
 */
class HomeworkTest extends TestCase
{
    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * Base passing test.
     */
    public function testIfTrueEqualsTue()
    {
        $this->assertTrue(true, 'Hurray!');
    }
}